/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace SOATest
{
  public enum Operation
  {
    ADD = 1,
    SUBSTRACT = 2,
    MULTIPLY = 3,
    DIVEDE = 4,
  }
}
